export const actionCourseTypes = {
  ADD_COURSE: "ADD_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  SET_COURSE_LIST: "SET_COURSE_LIST",
  SEARCH_COURSE: "SEARCH_COURSE",
  SHOW_EDIT_COURSE_MODAL: "SHOW_EDIT_COURSE_MODAL",
  SHOW_CREATE_COURSE_MODAL: "SHOW_CREATE_COURSE_MODAL",
};
