export const SIGN_IN_ACTION = "SIGN_IN_ACTION";
export const SET_UNREGIST_COURSE_USERLIST = "SET_UNREGIST_COURSE_USERLIST";
export const USER_EDIT = "USER_EDIT";
export const GET_INFO_USER_ACTION = "GET_INFO_USER_ACTION";
export const ADD_USER_ACTION = "ADD_USER_ACTION";
export const OPEN_MODAL = "OPEN_MODAL";