export const SIGN_IN_ACTION = "SIGN_IN_ACTION";

export const SET_UNREGIST_COURSE_USERLIST = "SET_UNREGIST_COURSE_USERLIST";
export const SET_REGISTED_COURSE_USERLIST = "SET_REGISTED_COURSE_USERLIST";

export const SET_COURSE_LIST_USER_UNREGIST = "SET_COURSE_LIST_USER_UNREGISTED";
export const SET_COURSE_LIST_USER_REGISTED = "SET_COURSE_LIST_USER_REGISTED";
export const SET_COURSE_LIST_UNAPPROVAL = "SET_COURSE_LIST_UNAPPROVAL";

export const GET_REGISTED_COURSE_CODE_NAME = "GET_REGISTED_COURSE_CODE_NAME";
export const GET_REGISTED_COURSE_NAME = "GET_REGISTED_COURSE_CODE_NAME";
export const GET_REGISTED_ACCOUNT_NAME = "GET_REGISTED_ACCOUNT_NAME";

export const USER_EDIT = "USER_EDIT";
export const GET_INFO_USER_ACTION = "GET_INFO_USER_ACTION";
export const ADD_USER_ACTION = "ADD_USER_ACTION";
export const ADD_USER_MODAL = "ADD_USER_MODAL";
export const EDIT_USER_MODAL = "EDIT_USER_MODAL";

export const SEARCH_USER = "SEARCH_USER";


